name: Standalone CLI

on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repository as safe directory
        run: git config --global --add safe.directory /github/workspace

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Fluid Attacks CLI
        run: |
          docker run --rm -v $(pwd):/github/workspace -w /github/workspace docker.io/fluidattacks/cli:latest skims scan --sarif --csv ./config.yaml

      - name: Upload all results
        uses: actions/upload-artifact@v2
        with:
            name: scan-results
            path: /github/workspace/
            if-no-files-found: warn          
