name: Standalone CLI

on: [push, pull_request]
jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - name: machineStandalone
        uses: docker://docker.io/fluidattacks/cli:latest
        with:
          args: skims scan --sarif --csv . 
      - name: List files
        run: ls /github/workspace/
      - name: show results
        run: cat /github/workspace/skims_results.sarif   