name: Standalone CLI

on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Fluid Attacks CLI
        uses: docker://docker.io/fluidattacks/cli:latest
        with:
          args: skims --restrict scan --sarif --csv ./config.yaml
